## Import Module

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Read data

In [ ]:
data = pd.read_csv('movies_metadata.csv')
data = pd.DataFrame(data)
data.head()

<ipython-input-4-15875c2f40a0>:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
data.loc[0]

adult                                                                False
belongs_to_collection    {'id': 10194, 'name': 'Toy Story Collection', ...
budget                                                            30000000
genres                   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
homepage                              http://toystory.disney.com/toy-story
id                                                                     862
imdb_id                                                          tt0114709
original_language                                                       en
original_title                                                   Toy Story
overview                 Led by Woody, Andy's toys live happily in his ...
popularity                                                       21.946943
poster_path                               /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
production_companies        [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-10-30
revenue                                                        373554033.0
runtime                                                               81.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                                NaN
title                                                            Toy Story
video                                                                False
vote_average                                                           7.7
vote_count                                                          5415.0
Name: 0, dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [ ]:
data.loc[:,['budget','original_title']]

         budget               original_title
0      30000000                    Toy Story
1      65000000                      Jumanji
2             0             Grumpier Old Men
3      16000000            Waiting to Exhale
4             0  Father of the Bride Part II
...         ...                          ...
45461         0                      رگ خواب
45462         0          Siglo ng Pagluluwal
45463         0                     Betrayal
45464         0          Satana likuyushchiy
45465         0                     Queerama

[45466 rows x 2 columns]

No charts were generated by quickchart

In [ ]:
data

adult  belongs_to_collection                                                                                                                                                   budget    genres                                                                                                                                                                   homepage                                                                   id      imdb_id    original_language  original_title                           overview                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                popularity  poster_path                       production_companies                                                                                                                                                                                                                                                                                                                production_countries                                                                                        release_date  revenue      runtime  spoken_languages                                                                                                                                                       status    tagline                                                     title                                    video  vote_average  vote_count
False  {'id': 10, 'name': 'Star Wars Collection', 'poster_path': '/ghd5zOQnDaDW1mxO7R5fXXpZMu.jpg', 'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'}                       11000000  [{'id': 12, 'name': 'Adventure'}, {'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}]                                                                  http://www.starwars.com/films/star-wars-episode-iv-a-new-hope              11      tt0076759  en                 Star Wars                                Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.                                                                                                                                                                                                                                                                                                                                                                                                                                                                42.149697   /btTdmkgIvOi0FFip1sPuZI2oQG6.jpg  [{'name': 'Lucasfilm', 'id': 1}, {'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]                                                                                                                                                                                                                                     [{'iso_3166_1': 'US', 'name': 'United States of America'}]                                                  1977-05-25    775398007.0  121.0    [{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                               Released  A long time ago in a galaxy far, far away...                Star Wars                                False  8.1           6778.0        1
       {'id': 4563, 'name': 'The Vengeance Collection', 'poster_path': '/ilyS5xmHzMtTq4ngVRNKvZEbSRo.jpg', 'backdrop_path': '/t5zZZOvXK8m5z1omMdEEWcL6ywl.jpg'}                0         [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]                                                                                                            http://www.lady-vengeance.de/                                              4550    tt0451094  ko                 친절한 금자씨                                  After a 13-year imprisonment for the kidnap and murder of a 6 year old boy, beautiful Lee Guem-ja starts seeking revenge on the man that was really responsible for the boy's death. With the help of fellow inmates and reunited with her daughter, she gets closer and closer to her goal. But will her actions lead to the relief she seeks?                                                                                                                                                                                                                                                                                                                                                                                                                                         7.400261    /vymGV0lscCGpaLjGyQhxkjq0jeg.jpg  [{'name': 'CJ Capital Investment', 'id': 946}, {'name': 'Korea Capital Investment', 'id': 1687}, {'name': 'Moho Films', 'id': 1688}, {'name': 'TSJ Entertainment', 'id': 1689}, {'name': 'Samsung Venture Capital', 'id': 1690}, {'name': 'Ilshin Capital Investments', 'id': 1691}, {'name': 'Centurion Investment', 'id': 1692}]  [{'iso_3166_1': 'KR', 'name': 'South Korea'}]                                                               2005-07-29    23803308.0   115.0    [{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'ja', 'name': '日本語'}, {'iso_639_1': 'ko', 'name': '한국어/조선말'}]                                                   Released  All she wanted was a peaceful life... they didn't give it.  Sympathy for Lady Vengeance              False  7.4           362.0         1
       {'id': 447622, 'name': 'Barbie Mariposa Collection', 'poster_path': '/zPy6dlkTA2RNUr5sJE0lBwtWHA7.jpg', 'backdrop_path': None}                                          0         [{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}]                                                                        http://www.barbie.com                                                      196254  tt2946582  en                 Barbie: Mariposa and The Fairy Princess  Mariposa and her furry friend Zee returns in Barbie: Mariposa &amp; the Fairy Princess. In this magical adventure, Mariposa becomes the Royal Ambassador of Flutterfield, and is sent to bring peace between her fairy land and their rivals, the Crystal Fairies of Shimmervale. While Mariposa doesn't make a great first impression on  the King, she becomes fast friends with his shy daughter, Princess Catania. However, a misunderstanding causes Mariposa to be banished from their fairy land. As Mariposa and Zee returns to Flutterfield, they encounter a dark fairy on her way to destroy Shimmervale. Mariposa rushes back and helps Princess Catania to save their fairy land and together, the two girls prove that the best way to make a friend, is to be a friend.  4.320534    /twxU1AxLsWphM9RIYJgy8PZ32ye.jpg  [{'name': 'Universal Studios', 'id': 13}]                                                                                                                                                                                                                                                                                           [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]  2013-08-26    0.0          75.0     [{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                               Released  Friendship overcomes any obstacle.                          Barbie: Mariposa and The Fairy Princess  False  6.3           43.0          1
       {'id': 448150, 'name': 'Deadpool Collection', 'poster_path': '/30c5jO7YEXuF8KiWXLg9m28GWDA.jpg', 'backdrop_path': '/hBQOWY8qWXJVFAc8yLTh1teIu43.jpg'}                   58000000  [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}]                                                                            http://www.foxmovies.com/movies/deadpool                                   293660  tt1431045  en                 Deadpool                                 Deadpool tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.                                                                                                                                                                                                                                                                                                                                                                                                                            187.860492  /inVq3FRqcYIRl2la8iZikYYxFNR.jpg  [{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}, {'name': 'Marvel Entertainment', 'id': 7505}, {'name': "The Donners' Company", 'id': 11307}, {'name': 'TSG Entertainment', 'id': 22213}, {'name': 'Kinberg Genre', 'id': 78091}]                                                                                    [{'iso_3166_1': 'US', 'name': 'United States of America'}]                                                  2016-02-09    783112979.0  108.0    [{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                               Released  Witness the beginning of a happy ending                     Deadpool                                 False  7.4           11444.0       1
       {'id': 44976, 'name': 'Dhoom Series', 'poster_path': '/qc1R0oO2tb7TFPiql7Aq6QoDwJp.jpg', 'backdrop_path': None}                                                         11000000  [{'id': 18, 'name': 'Drama'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}]                                                 http://www.yashrajfilms.com/microsites/dhoom2/d2micro/microflash.htm       14194   tt0441048  en                 Dhoom 2                                  In the second installment of the Dhoom series, Jai and Ali are back as the buddy cops on their toughest job so far. "Mr.A" is an international thief who has planned to steal a priceless artifact in Mumbai and the police have got to nab him. But Mr.A manages to steal the artifact and elude the police. He finds his match in Sunehri and they form a partnership. They move on to Rio for their next job, with Jai and Ali hot on their trail. Mr.A whose actual name is Aryan, and Sunehri are drawn towards each other but little does Aryan know of Sunehri's little secret.                                                                                                                                                                                                  3.81393     /cwesb18fxJ4kFN7w1qVnhlPDkTo.jpg  [{'name': 'Yash Raj Films', 'id': 1569}]                                                                                                                                                                                                                                                                                            [{'iso_3166_1': 'IN', 'name': 'India'}]                                                                     2006-11-24    46396427.0   147.0    [{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso_639_1': 'hi', 'name': 'हिन्दी'}]                                                                                        Released  Diwali 2006: Dhoom Machale once again!                      Dhoom 2                                  False  5.9           69.0          1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
       {'id': 255478, 'name': "Cowgirls n' Angels Collection", 'poster_path': '/p8hwMZbeNe6qQFlblm1DjKrvYOu.jpg', 'backdrop_path': None}                                       0         [{'id': 10751, 'name': 'Family'}]                                                                                                                                        http://www.dakotassummer.com/                                              255476  tt2910342  en                 Dakota's Summer                          Cowgirls 'n Angels Dakota's Summer tells the story of Dakota Rose, a cowgirl and competitive trick rider who finds out at the age of seventeen that she was adopted. She secretly sets out to discover the truth about her adoption and meet her birth parents while visiting her grandfather, rodeo legend Austin Rose. At Austin's ranch on break from the Sweethearts of the Rodeo trick riding team, Dakota discovers that family is not defined by blood, but rather personal commitment and by the love they share. Finally at peace, Dakota trains with Austin in order to prepare to rejoin the Sweethearts for their final competition against the talented Lone Star trick riding team and become the champion trick rider she was destined to be.                            1.076293    /gq7YGGHjeBlIk9LSVBPa32u12bj.jpg  []                                                                                                                                                                                                                                                                                                                                  [{'iso_3166_1': 'US', 'name': 'United States of America'}]                                                  2014-04-17    0.0          91.0     [{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                               Released  Sometimes you win. Sometimes you learn.                     Dakota's Summer                          False  5.8           11.0          1
                                                                                                                                                                                         [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]                                                                                                           http://www.facebook.com/cowgirlsnangels                                    105528  tt1894561  en                 Cowgirls n' Angels                       A group of rodeo trick-riders recruits a young girl to join them.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2.490032    /ctSRKSeB57JQSvvGvdBoWgFxniy.jpg  []                                                                                                                                                                                                                                                                                                                                  [{'iso_3166_1': 'US', 'name': 'United States of America'}]                                                  2012-05-25    120680.0     92.0     [{'iso_639_1': 'en', 'name': 'English'}]                                                                                                                               Released  Dreams come true.                                           Cowgirls n' Angels                       False  5.3           15.0          1

In [ ]:
data.duplicated().sum()

13

In [ ]:
data.loc["Toy Story"]

adult                                                                False
belongs_to_collection    {'id': 10194, 'name': 'Toy Story Collection', ...
budget                                                            30000000
genres                   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
homepage                              http://toystory.disney.com/toy-story
id                                                                     862
imdb_id                                                          tt0114709
original_language                                                       en
overview                 Led by Woody, Andy's toys live happily in his ...
popularity                                                       21.946943
poster_path                               /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
production_companies        [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-10-30
revenue                                                        373554033.0
runtime                                                               81.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                                NaN
title                                                            Toy Story
video                                                                False
vote_average                                                           7.7
vote_count                                                          5415.0
Name: Toy Story, dtype: object

In [ ]:
data = data.reset_index()

In [ ]:
data.columns

Index(['original_title', 'adult', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'original_language', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
data.loc[:,["original_title","budget","genres"]]

,original_title,budget,genres
0,Toy Story,30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '..."
1,Jumanji,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '..."
2,Grumpier Old Men,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ..."
3,Waiting to Exhale,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
4,Father of the Bride Part II,0,"[{'id': 35, 'name': 'Comedy'}]"
...,...,...,...
45461,رگ خواب,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n..."
45462,Siglo ng Pagluluwal,0,"[{'id': 18, 'name': 'Drama'}]"
45463,Betrayal,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam..."
45464,Satana likuyushchiy,0,[]
45465,Queerama,0,[]